/**
 * @fileoverview Pull-Env Command
 * @description After admin approves a registration request, fetch all credentials
 * (client_id, client_secret, redirect URLs, realm, etc.) and write them to .env.
 * This works for both new and already-developed applications.
 *
 * Usage:
 *   sso-client pull-env <clientKey> --email <developerEmail>
 *   sso-client pull-env  (auto-detects clientKey and email from existing .env)
 */

import fs from 'fs';
import chalk from 'chalk';
import { authApi } from '../services/api.js';
import { SSO_CONFIG } from '../config/index.js';
import { logger } from '../utils/logger.js';

/**
 * Auto-detect clientKey and developerEmail from existing .env if present
 * @param {string|undefined} clientKeyArg
 * @param {string|undefined} emailArg
 * @returns {{ clientKey: string|null, developerEmail: string|null }}
 */
function resolveArgs(clientKeyArg, emailArg) {
    let clientKey = clientKeyArg || null;
    let developerEmail = emailArg || null;

    if (fs.existsSync('.env')) {
        const envContent = fs.readFileSync('.env', 'utf-8');

        if (!clientKey) {
            const match = envContent.match(/VITE_CLIENT_KEY=(.+)/);
            if (match) clientKey = match[1].trim();
        }

        if (!developerEmail) {
            const match = envContent.match(/SSO_DEVELOPER_EMAIL=(.+)/);
            if (match) developerEmail = match[1].trim();
        }
    }

    return { clientKey, developerEmail };
}

/**
 * Write the full .env file after credentials are retrieved
 * @param {Object} credentials - From /auth/clients/:clientKey/credentials
 * @param {boolean} useDockerUrls - Whether to use portless URLs
 * @param {string|number} port - Dev port (only used if not Docker)
 */
function writeFullEnv(credentials, useDockerUrls, port) {
    const authBaseUrl = useDockerUrls
        ? `${SSO_CONFIG.protocol}://auth.${SSO_CONFIG.domain}`
        : SSO_CONFIG.authServiceUrl;

    const accountUiUrl = useDockerUrls
        ? `${SSO_CONFIG.protocol}://account.${SSO_CONFIG.domain}`
        : SSO_CONFIG.accountUiUrl;

    const envLines = [
        `# SSO Configuration - generated by sso-client pull-env`,
        `# Generated: ${new Date().toISOString()}`,
        ``,
        `# ── Application ──────────────────────────────────────────────────────────────`,
        `VITE_CLIENT_KEY=${credentials.client_key}`,
        `VITE_APP_NAME=${credentials.client_key}`,
        useDockerUrls ? null : `VITE_PORT=${port}`,
        ``,
        `# ── Auth Service URLs ─────────────────────────────────────────────────────────`,
        `VITE_AUTH_BASE_URL=${authBaseUrl}`,
        `VITE_ACCOUNT_UI_URL=${accountUiUrl}`,
        `VITE_REDIRECT_URI=${credentials.redirect_url}`,
        ``,
        `# ── SSO / Keycloak Credentials ───────────────────────────────────────────────`,
        `# These are used by auth-service for token exchange. Keep CLIENT_SECRET server-side only.`,
        `VITE_SSO_REALM=${credentials.realm}`,
        `SSO_CLIENT_ID=${credentials.client_id}`,
        `SSO_CLIENT_SECRET=${credentials.client_secret}`,
        `SSO_CALLBACK_URL=${credentials.callback_url}`,
        ``,
        `# ── Organization ─────────────────────────────────────────────────────────────`,
        `VITE_REQUIRES_ORGANIZATION=${credentials.requires_organization ? 'true' : 'false'}`,
        `VITE_ORGANIZATION_MODEL=${credentials.organization_model || 'none'}`,
        `VITE_ONBOARDING_FLOW=${credentials.onboarding_flow || 'none'}`,
        ``,
        `# ── Environment ──────────────────────────────────────────────────────────────`,
        `NODE_ENV=${useDockerUrls ? 'production' : 'development'}`,
        `NODE_TLS_REJECT_UNAUTHORIZED=0`,
    ].filter(line => line !== null);

    fs.writeFileSync('.env', envLines.join('\n') + '\n');
}

/**
 * Execute pull-env command
 * Fetches approved client credentials and writes the complete .env
 * @param {string|undefined} clientKeyArg - CLI argument
 * @param {Object} options - Commander options (options.email)
 */
export async function pullEnvCommand(clientKeyArg, options = {}) {
    const { clientKey, developerEmail } = resolveArgs(clientKeyArg, options.email);

    if (!clientKey) {
        logger.error('Client key required');
        logger.info('Usage: sso-client pull-env <clientKey> --email <developerEmail>');
        logger.info('Or run from a directory with a .env containing VITE_CLIENT_KEY');
        process.exit(1);
    }

    if (!developerEmail) {
        logger.error('Developer email required');
        logger.info(`Usage: sso-client pull-env ${clientKey} --email <developerEmail>`);
        process.exit(1);
    }

    logger.step(`🔑 Fetching credentials for: ${clientKey}\n`);

    try {
        const { credentials } = await authApi.getClientCredentials(clientKey, developerEmail);

        // Detect Docker/production from existing .env or infer from redirect_url
        let useDockerUrls = SSO_CONFIG.dockerMode;
        let port = '5173';

        if (fs.existsSync('.env')) {
            const envContent = fs.readFileSync('.env', 'utf-8');
            const portMatch = envContent.match(/VITE_PORT=(\d+)/);
            if (portMatch) port = portMatch[1];

            // If redirect_url has no port, assume Docker/production
            if (credentials.redirect_url && !/:\d+/.test(credentials.redirect_url)) {
                useDockerUrls = true;
            }
        }

        writeFullEnv(credentials, useDockerUrls, port);

        logger.success('.env updated with full credentials\n');

        logger.section('Values Written to .env');
        logger.keyValue('Client ID', credentials.client_id);
        logger.keyValue('Client Secret', credentials.client_secret.slice(0, 8) + '••••••••••••••••••••••••');
        logger.keyValue('Realm', credentials.realm);
        logger.keyValue('Redirect URL', credentials.redirect_url);
        logger.keyValue('Callback URL', credentials.callback_url);

        if (credentials.requires_organization) {
            logger.keyValue('Organization Model', credentials.organization_model);
            logger.keyValue('Onboarding Flow', credentials.onboarding_flow);
        }

        logger.blank();
        logger.section('Security Note');
        console.log(chalk.yellow('⚠  SSO_CLIENT_SECRET is written to .env for convenience.'));
        console.log(chalk.yellow('   For production, move it to a secrets manager or server-side env only.'));
        console.log(chalk.yellow('   Do NOT commit .env to version control.'));

        logger.blank();
        logger.section('Next Steps');
        console.log(chalk.white('1. Review .env and adjust VITE_PORT / NODE_ENV as needed'));
        console.log(chalk.white('2. Add to /etc/hosts (local dev):'));
        console.log(chalk.gray(`   echo "127.0.0.1 ${credentials.client_key}.${SSO_CONFIG.domain}" | sudo tee -a /etc/hosts`));
        console.log(chalk.white('3. Start your application'));

    } catch (error) {
        if (error.message?.includes('Not approved') || error.message?.includes('not approved')) {
            logger.error('Client is not approved yet');
            logger.info(`Check status: sso-client status ${clientKey}`);
        } else if (error.message?.includes('Forbidden') || error.message?.includes('does not match')) {
            logger.error('Developer email does not match the registered email for this client');
            logger.info('Use the same email address you provided when registering this client');
        } else if (error.message?.includes('Not found')) {
            logger.error(`No record found for client key: ${clientKey}`);
            logger.info('Register first: sso-client register');
        } else {
            logger.error('Failed to fetch credentials:', error.message);
        }
        process.exit(1);
    }
}

export default pullEnvCommand;
