/**
 * Roles API Client
 * 
 * Auto-generated by sso-cli-tools
 * Client: author
 * 
 * Handles CRUD operations for custom organization-scoped roles
 */

import { auth } from '@spidy092/auth-client';

/**
 * Get current organization ID from storage
 */
function getOrgId() {
  try {
    const orgData = localStorage.getItem('sso.currentOrganization');
    if (orgData) {
      const org = JSON.parse(orgData);
      return org.id || org.org_id || '';
    }
  } catch (e) {
    console.error('Failed to parse organization from storage:', e);
  }
  return '';
}

/**
 * List all roles (system + custom) for current organization
 */
export async function getRoles() {
  try {
    const response = await auth.api.get('/db-roles');
    const data = response.data?.data || response.data || [];
    return Array.isArray(data) ? data : (data.roles || []);
  } catch (error) {
    console.error('Failed to fetch roles:', error);
    throw error;
  }
}

/**
 * Get single role details
 */
export async function getRole(roleId) {
  try {
    const response = await auth.api.get(`/db-roles/${roleId}`);
    return response.data?.data?.role || response.data?.role || response.data;
  } catch (error) {
    console.error('Failed to fetch role:', error);
    throw error;
  }
}

/**
 * Create a new custom role
 */
export async function createRole({ name, description, permissions = [] }) {
  const orgId = getOrgId();

  try {
    const response = await auth.api.post('/db-roles', {
      name,
      description,
      permissions,
      is_system: false
    });
    return response.data?.data?.role || response.data?.role || response.data;
  } catch (error) {
    console.error('Failed to create role:', error);
    throw error;
  }
}

/**
 * Update an existing role
 */
export async function updateRole(roleId, updates) {
  try {
    const response = await auth.api.patch(`/db-roles/${roleId}`, updates);
    return response.data?.data?.role || response.data?.role || response.data;
  } catch (error) {
    console.error('Failed to update role:', error);
    throw error;
  }
}

/**
 * Delete a custom role
 */
export async function deleteRole(roleId) {
  try {
    await auth.api.delete(`/db-roles/${roleId}`);
    return true;
  } catch (error) {
    console.error('Failed to delete role:', error);
    throw error;
  }
}

/**
 * Assign permissions to a role
 */
export async function assignPermissions(roleId, permissionIds) {
  try {
    const response = await auth.api.put(`/db-roles/${roleId}/permissions`, {
      permission_ids: permissionIds
    });
    return response.data?.data || response.data;
  } catch (error) {
    console.error('Failed to assign permissions:', error);
    throw error;
  }
}

/**
 * Get available permissions
 */
export async function getAvailablePermissions() {
  try {
    // Permissions are at /permissions endpoint, not /db-roles/permissions
    const response = await auth.api.get('/permissions');
    const data = response.data?.data || response.data;
    return Array.isArray(data) ? data : (data.permissions || []);
  } catch (error) {
    console.error('Failed to fetch permissions:', error);
    // Return empty array instead of failing completely
    return [];
  }
}

/**
 * Assign role to organization member
 */
export async function assignRoleToMember(memberId, roleId) {
  const orgId = getOrgId();

  try {
    const response = await auth.api.put(`/organizations/${orgId}/members/${memberId}/role`, {
      role_id: roleId
    });
    return response.data?.data || response.data;
  } catch (error) {
    console.error('Failed to assign role:', error);
    throw error;
  }
}

export default {
  getRoles,
  getRole,
  createRole,
  updateRole,
  deleteRole,
  assignPermissions,
  getAvailablePermissions,
  assignRoleToMember,
};
