/**
 * Member Role Assignment Component
 * 
 * Auto-generated by sso-cli-tools
 * 
 * Allows admins to assign roles to organization members
 */

import { useState } from 'react';
import {
  Box,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Button,
  Chip,
  CircularProgress,
  Alert,
} from '@mui/material';
import { assignRoleToMember } from '../../api/roles';

export default function MemberRoleAssignment({ member, roles, onUpdate }) {
  const [selectedRoleId, setSelectedRoleId] = useState(member.role_id || '');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);

  const handleAssignRole = async () => {
    if (!selectedRoleId) return;
    
    try {
      setLoading(true);
      setError(null);
      await assignRoleToMember(member.id, selectedRoleId);
      setSuccess(true);
      if (onUpdate) onUpdate();
      setTimeout(() => setSuccess(false), 3000);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const currentRole = roles.find(r => r.id === member.role_id);

  return (
    <Box display="flex" alignItems="center" gap={2}>
      {error && (
        <Alert severity="error" size="small" onClose={() => setError(null)}>
          {error}
        </Alert>
      )}
      
      {success && (
        <Alert severity="success" size="small">
          Role updated!
        </Alert>
      )}

      <Chip
        label={currentRole?.name || 'No role'}
        color={currentRole?.is_system ? 'primary' : 'secondary'}
        size="small"
      />

      <FormControl size="small" sx={{ minWidth: 150 }}>
        <InputLabel>Change Role</InputLabel>
        <Select
          value={selectedRoleId}
          label="Change Role"
          onChange={(e) => setSelectedRoleId(e.target.value)}
          disabled={loading}
        >
          {roles.map((role) => (
            <MenuItem key={role.id} value={role.id}>
              {role.name}
              {role.is_system && ' (System)'}
            </MenuItem>
          ))}
        </Select>
      </FormControl>

      <Button
        variant="outlined"
        size="small"
        onClick={handleAssignRole}
        disabled={loading || !selectedRoleId || selectedRoleId === member.role_id}
      >
        {loading ? <CircularProgress size={20} /> : 'Assign'}
      </Button>
    </Box>
  );
}
