# ============================================================================
# Super Admin Server (Organization Management)
# ============================================================================

server {
    listen 443 ssl;
    http2 on;

    server_name org.local.test;

    # Health
    # This is a simple health check endpoint, to check if the server is up or not
    location = /_healthz {
        access_log off;
        default_type application/json;
        return 200 '{"status":"ok"}';
    }

    include /etc/nginx/snippets/error_response.conf;

    # -------------------------
    # Dynamic routed entrypoint
    # -------------------------

    location / {
        default_type application/json;

        # Basic abuse protection
        limit_req zone=req_limit burst=20 nodelay;

        # Only allow common methods
        limit_except GET POST PUT PATCH DELETE HEAD OPTIONS { deny all; }

        include /etc/nginx/snippets/proxy_headers.conf;
        include /etc/nginx/snippets/security_headers.conf;
        # Handle preflight OPTIONS requests
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, Accept, Origin' always;
            add_header 'Content-Length' 0 always;
            return 204;
        }

        # Use variable to force runtime DNS resolution
        set $upstream_admin super-administrator:4010;
        proxy_pass http://$upstream_admin;
    }
}