# ============================================================================
# Email Service API
# ============================================================================

server {
    listen 80;

    server_name email.gururajhr.in;

    # Health
    location = /_healthz {
        access_log off;
        default_type application/json;
        return 200 '{"status":"ok"}';
    }

    include /etc/nginx/snippets/error_response.conf;

    # -------------------------
    # Dynamic routed entrypoint
    # -------------------------

    location / {
        default_type application/json;

        # Basic abuse protection
        limit_req zone=req_limit burst=20 nodelay;

        # Only allow common methods
        limit_except GET POST PUT PATCH DELETE HEAD OPTIONS { deny all; }

        include /etc/nginx/snippets/proxy_headers.conf;
        include /etc/nginx/snippets/security_headers.conf;

        proxy_pass http://email_service;
    }
}
