/**
 * Roles API Client
 * 
 * Auto-generated by sso-cli-tools
 * Client: {{clientId}}
 * 
 * Handles CRUD operations for custom organization-scoped roles
 */

const API_BASE = import.meta.env.VITE_AUTH_BASE_URL || '';

/**
 * Get auth headers
 */
function getHeaders() {
  const token = localStorage.getItem('accessToken');
  const orgId = localStorage.getItem('currentOrgId');
  
  return {
    'Content-Type': 'application/json',
    'Authorization': token ? `Bearer ${token}` : '',
    'X-Org-Id': orgId || '',
  };
}

/**
 * List all roles (system + custom) for current organization
 */
export async function getRoles() {
  const response = await fetch(`${API_BASE}/api/org-roles`, {
    headers: getHeaders(),
  });
  
  if (!response.ok) {
    throw new Error('Failed to fetch roles');
  }
  
  const data = await response.json();
  return data.roles || data.data?.roles || [];
}

/**
 * Get single role details
 */
export async function getRole(roleId) {
  const response = await fetch(`${API_BASE}/api/org-roles/${roleId}`, {
    headers: getHeaders(),
  });
  
  if (!response.ok) {
    throw new Error('Failed to fetch role');
  }
  
  const data = await response.json();
  return data.role || data.data?.role;
}

/**
 * Create a new custom role
 */
export async function createRole({ name, description, permissions = [] }) {
  const response = await fetch(`${API_BASE}/api/org-roles`, {
    method: 'POST',
    headers: getHeaders(),
    body: JSON.stringify({ name, description, permissions }),
  });
  
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || 'Failed to create role');
  }
  
  const data = await response.json();
  return data.role || data.data?.role;
}

/**
 * Update an existing custom role
 */
export async function updateRole(roleId, { name, description }) {
  const response = await fetch(`${API_BASE}/api/org-roles/${roleId}`, {
    method: 'PUT',
    headers: getHeaders(),
    body: JSON.stringify({ name, description }),
  });
  
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || 'Failed to update role');
  }
  
  const data = await response.json();
  return data.role || data.data?.role;
}

/**
 * Delete a custom role
 */
export async function deleteRole(roleId) {
  const response = await fetch(`${API_BASE}/api/org-roles/${roleId}`, {
    method: 'DELETE',
    headers: getHeaders(),
  });
  
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || 'Failed to delete role');
  }
  
  return true;
}

/**
 * Assign permissions to a role
 */
export async function assignPermissions(roleId, permissions) {
  const response = await fetch(`${API_BASE}/api/org-roles/${roleId}/permissions`, {
    method: 'POST',
    headers: getHeaders(),
    body: JSON.stringify({ permissions }),
  });
  
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || 'Failed to assign permissions');
  }
  
  const data = await response.json();
  return data.role || data.data?.role;
}

/**
 * Get available permissions
 */
export async function getAvailablePermissions() {
  const response = await fetch(`${API_BASE}/api/org-roles/permissions/available`, {
    headers: getHeaders(),
  });
  
  if (!response.ok) {
    throw new Error('Failed to fetch permissions');
  }
  
  const data = await response.json();
  return data.permissions || data.data?.permissions || [];
}

/**
 * Assign role to organization member
 */
export async function assignRoleToMember(memberId, roleId) {
  const orgId = localStorage.getItem('currentOrgId');
  
  const response = await fetch(`${API_BASE}/auth/organizations/${orgId}/members/${memberId}/role`, {
    method: 'PUT',
    headers: getHeaders(),
    body: JSON.stringify({ role_id: roleId }),
  });
  
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || 'Failed to assign role');
  }
  
  return true;
}

export default {
  getRoles,
  getRole,
  createRole,
  updateRole,
  deleteRole,
  assignPermissions,
  getAvailablePermissions,
  assignRoleToMember,
};
