/**
 * RBAC Middleware - Authorization Hook
 * 
 * Auto-generated by sso-cli-tools
 * Client: {{clientId}}
 * 
 * Usage:
 *   import { useAuth, useHasPermission } from './hooks/useAuth';
 *   const canEdit = useHasPermission(PERMISSIONS.ORG.UPDATE);
 */

import { useAuth } from './useAuth';
import { PERMISSIONS } from '../constants/permissions';

/**
 * Check if current user has a specific permission
 * @param {string} permission - Permission string (e.g., '*:org:read')
 * @returns {boolean}
 */
export function useHasPermission(permission) {
  const { user } = useAuth();
  
  if (!user?.permissions) return false;
  
  // Check for exact match or wildcard permission
  return user.permissions.includes(permission) || 
         user.permissions.includes('*:*:*');
}

/**
 * Check if current user has any of the specified permissions
 * @param {string[]} permissions - Array of permission strings
 * @returns {boolean}
 */
export function useHasAnyPermission(permissions) {
  const { user } = useAuth();
  
  if (!user?.permissions) return false;
  if (user.permissions.includes('*:*:*')) return true;
  
  return permissions.some(p => user.permissions.includes(p));
}

/**
 * Check if current user has all specified permissions
 * @param {string[]} permissions - Array of permission strings
 * @returns {boolean}
 */
export function useHasAllPermissions(permissions) {
  const { user } = useAuth();
  
  if (!user?.permissions) return false;
  if (user.permissions.includes('*:*:*')) return true;
  
  return permissions.every(p => user.permissions.includes(p));
}

/**
 * Check if current user has a specific role
 * @param {string} role - Role name (e.g., 'admin')
 * @returns {boolean}
 */
export function useHasRole(role) {
  const { user } = useAuth();
  return user?.role === role || user?.roles?.includes(role);
}

/**
 * PermissionGate component - conditionally render children based on permission
 * 
 * Usage:
 *   <PermissionGate permission={PERMISSIONS.MEMBER.INVITE}>
 *     <InviteButton />
 *   </PermissionGate>
 */
export function PermissionGate({ permission, permissions, requireAll = false, fallback = null, children }) {
  let hasAccess = false;
  
  if (permission) {
    hasAccess = useHasPermission(permission);
  } else if (permissions) {
    hasAccess = requireAll 
      ? useHasAllPermissions(permissions)
      : useHasAnyPermission(permissions);
  }
  
  return hasAccess ? children : fallback;
}

export { PERMISSIONS };
