/**
 * RBAC Permission Constants
 * 
 * Auto-generated by sso-cli-tools
 * Client: {{clientId}}
 * 
 * Usage:
 *   import { PERMISSIONS } from './constants/permissions';
 *   authorizeRBAC(PERMISSIONS.ORG.READ);
 */

export const PERMISSIONS = {
  // Organization permissions
  ORG: {
    READ: '*:org:read',
    UPDATE: '*:org:update',
    DELETE: '*:org:delete',
  },

  // Member management
  MEMBER: {
    READ: '*:member:read',
    INVITE: '*:member:invite',
    REMOVE: '*:member:remove',
    UPDATE_ROLE: '*:member:update_role',
  },

  // Workspace permissions
  WORKSPACE: {
    CREATE: '*:workspace:create',
    READ: '*:workspace:read',
    UPDATE: '*:workspace:update',
    DELETE: '*:workspace:delete',
    MEMBER_ADD: '*:workspace:member:add',
    MEMBER_REMOVE: '*:workspace:member:remove',
  },

  // Role management
  ROLE: {
    CREATE: '*:role:create',
    READ: '*:role:read',
    UPDATE: '*:role:update',
    DELETE: '*:role:delete',
  },

  // Audit logs
  AUDIT: {
    READ: '*:audit:read',
  },
};

// System roles that users can be assigned
export const SYSTEM_ROLES = {
  OWNER: 'owner',
  ADMIN: 'admin',
  MEMBER: 'member',
  VIEWER: 'viewer',
};

// Role to permissions mapping (reference only)
export const ROLE_PERMISSIONS = {
  owner: ['*:*:*'],
  admin: [
    PERMISSIONS.ORG.READ,
    PERMISSIONS.ORG.UPDATE,
    PERMISSIONS.MEMBER.READ,
    PERMISSIONS.MEMBER.INVITE,
    PERMISSIONS.MEMBER.REMOVE,
    PERMISSIONS.MEMBER.UPDATE_ROLE,
    PERMISSIONS.WORKSPACE.CREATE,
    PERMISSIONS.WORKSPACE.READ,
    PERMISSIONS.WORKSPACE.UPDATE,
    PERMISSIONS.WORKSPACE.DELETE,
    PERMISSIONS.WORKSPACE.MEMBER_ADD,
    PERMISSIONS.WORKSPACE.MEMBER_REMOVE,
    PERMISSIONS.ROLE.READ,
    PERMISSIONS.AUDIT.READ,
  ],
  member: [
    PERMISSIONS.ORG.READ,
    PERMISSIONS.MEMBER.READ,
    PERMISSIONS.WORKSPACE.READ,
  ],
  viewer: [
    PERMISSIONS.ORG.READ,
    PERMISSIONS.WORKSPACE.READ,
  ],
};

export default PERMISSIONS;
